project:
  type: website

website:
  title: "NHL Shot Position Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
        text: Key Findings
      - href: exploration.qmd
        text: Shots by Season
      - href: pandemic.qmd
        text: Pandemic
      - href: lockout.qmd
        text: 2012 Lockout
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light:
        - cosmo
        - theme-light.scss
      dark:
        - cosmo
        - theme-dark.scss
    respect-user-color-scheme: true
    css: styles.css
    toc: true



